//! HTTP route table for the control-plane service: maps every path to its domain handler.
//! Kept out of `main.rs` so the composition root stays small and the surface is reviewable in one place.

use crate::state::AppState;
use crate::handlers::{
    packs::*, models::*, identity::*, approvals::*, policy::*, firewall::*, endpoints::*, grc::*, assurance::*, monitoring::*, evidence::*, reports::*, tickets::*, breakglass::*, console::*,
};
use crate::auth::dev_token;
use axum::{routing::{get, post}, Router};
use std::sync::Arc;

/// Build the fully-wired axum router with every route and the shared application state.
pub(crate) fn build_router(state: Arc<AppState>) -> Router {
    Router::new()
            .route("/", get(spa_index))
            // The Vue console assets (flat, stable filenames from console/dist). Deep links like
            // /overview are handled by the SPA fallback below, which returns index.html.
            .route("/main.js", get(asset))
            .route("/main.css", get(asset))
            .route("/favicon.svg", get(asset))
            .route("/inbox", get(inbox))
            .route("/healthz", get(|| async { "ok" }))
            .route("/readyz", get(|| async { "ready" }))
            .route("/approvals/register", post(approval_register))
            .route("/approvals/:id/status", get(approval_status))
            .route("/approvals/:id/approve", post(approve))
            .route("/approvals/:id/deny", post(deny))
            .route("/policy/current", get(policy_current))
            .route("/verify", get(verify))
            .route("/report", get(report))
            .route("/metrics", get(metrics))
            .route("/heartbeat/:proxy", post(heartbeat))
            .route("/liveness", get(liveness))
            .route("/event/:kind", post(record_event))
            .route("/tickets/callback", post(ticket_callback))
            .route("/tickets/jira", post(ticket_jira))
            .route("/monitor/drift", get(monitor_drift_get).post(monitor_drift_post))
            .route("/monitor/lineage", get(monitor_lineage_get).post(monitor_lineage_post))
            .route("/alerts", get(alerts))
            .route("/events/recent", get(events_recent))
            .route("/report/violations", get(report_violations))
            .route("/report/framework/:name", get(report_framework))
            .route("/report/framework/:name/csv", get(report_framework_csv))
            .route("/report/framework/:name/pack", get(report_framework_pack))
            .route("/report/framework/:name/snapshot", post(report_framework_snapshot))
            .route("/report/framework/:name/history", get(report_framework_history))
            .route("/report/post-market", get(report_post_market))
            .route("/report/post-market/snapshot", post(report_post_market_snapshot))
            .route("/report/post-market/history", get(report_post_market_history))
            .route("/report/violations.csv", get(report_violations_csv))
            .route("/evidence/ingest", post(evidence_ingest))
            .route("/evidence/ingested", get(evidence_ingested))
            .route("/admin/meta", post(record_meta))
            .route("/meta-audit", get(meta_audit))
            .route("/timeline", get(timeline))
            .route("/apps", get(apps))
            .route("/agents", get(agents))
            .route("/policy-store", get(policy_store_current))
            .route("/policy-store/rules", get(policy_store_rules))
        .route("/policy-store/signed", get(policy_store_signed))
            .route("/policy-store/deploy", post(policy_store_deploy))
            .route("/policy/suggest", get(policy_suggest))
            .route("/endpoints", get(endpoints_list))
            .route("/endpoints/register", post(endpoints_register))
            .route("/intercept/rules", get(intercept_rules))
            .route("/firewall/config", get(firewall_config_get).post(firewall_config_set))
            .route("/firewall/threat-pack", post(threat_pack_load))
            .route("/firewall/threat-pack/available", get(threat_pack_available))
            .route("/firewall/rules", get(firewall_rules_list).post(firewall_rules_add))
            .route("/firewall/rules/:id/delete", post(firewall_rules_delete))
            .route("/apps", post(app_register))
            .route("/agents", post(agent_register))
            .route("/agents/:id/deactivate", post(agent_deactivate))
            .route("/agents/:id/auto-assess", post(agent_auto_assess))
        .route("/agent-config/:group", get(agent_config_get).post(agent_config_set))
        .route("/groups", get(groups_list).post(group_register))
            .route("/agents/verify", post(agent_verify))
            .route("/grc", get(grc_list).post(grc_create))
            .route("/grc/templates", get(grc_templates))
            .route("/redteam/run", post(redteam_run))
            .route("/redteam/runs", get(redteam_runs))
            .route("/oversight", get(oversight_get))
            .route("/oversight/config", post(oversight_config_post))
            .route("/oversight/scan", post(oversight_scan))
            .route("/policy/author", post(policy_author))
            .route("/models/:id/fairness", post(model_fairness))
            .route("/trust", get(trust_summary))
            .route("/audit/pack", get(audit_pack))
            .route("/incident/promote", post(incident_promote))
            .route("/memory/write", post(memory_write))
            .route("/retrieval/check", post(retrieval_check))
            .route("/delegation/verify", post(delegation_verify))
            .route("/credential/stamp", post(credential_stamp))
            .route("/redteam/target", post(redteam_target))
            .route("/grc/assess", post(grc_assess))
            .route("/grc/risk", post(grc_risk))
            .route("/grc/model-card", post(grc_model_card))
            .route("/grc/:id/status", post(grc_status))
            .route("/grc/:id/usecase/:stage", post(grc_usecase_transition))
            .route("/grc/:id/assign", post(grc_assign))
            .route("/grc/:id/link", post(grc_link))
            .route("/grc/:id/comments", get(grc_comments_get).post(grc_comments_post))
            .route("/grc/:id/control/:control_id", post(grc_control_toggle))
            .route("/approvals/pending", get(approvals_pending))
            .route("/evidence/recent", get(evidence_recent))
            .route("/break-glass", get(break_glass_status))
            .route("/break-glass/engage", post(break_glass_engage))
            .route("/break-glass/clear", post(break_glass_clear))
            .route("/packs", get(packs_list).post(pack_load))
            .route("/packs/available", get(packs_available))
            .route("/controls", get(controls_list))
            .route("/models", get(models_list).post(model_register))
            .route("/models/:id", get(model_get))
            .route("/vendors", get(vendors_list).post(vendor_register))
            .route("/vendors/:id/review", post(vendor_review))
            .route("/leader", get(leader_status))
            .route("/tenants", get(tenants_list))
            .route("/scim/v2/Users", get(scim_users))
        .route("/principal/groups", get(principal_groups))
            .route("/scim/v2/Groups", get(scim_groups))
            .route("/auth/dev-token", get(dev_token))
        .fallback(spa_fallback)
            .with_state(state)
}
