//! Content credentials for generated media (gap G11, C2PA-style).
//!
//! A transparency obligation can require generated content to be labelled and its provenance stamped,
//! with proof recorded in the ledger. This is a minimal, verifiable content-credential manifest: a
//! signed statement binding a hash of the content to its declared provenance (the disclosure that it
//! is AI-generated, the model, and a timestamp). It is not the full C2PA spec, but it is a real signed
//! provenance record that a verifier checks with the public key alone.

use crate::sign::{verify_ed25519, Signer};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ContentCredential {
    pub manifest: Value,
    pub algo: String,
    pub pubkey_hex: String,
    pub sig_hex: String,
}

/// Stamp a content credential over the content bytes and the declared provenance.
pub fn stamp(content: &[u8], model: &str, disclosure: &str, ts_ms: u64, signer: &dyn Signer) -> ContentCredential {
    let manifest = json!({
        "spec": "acp-content-credential/1",
        "content_sha256": crate::canonical::sha256_hex_bytes(content),
        "ai_generated": true,
        "disclosure": disclosure,
        "model": model,
        "ts_ms": ts_ms,
    });
    let bytes = crate::canonical::canonical_bytes(&manifest);
    let sig = signer.sign(&bytes);
    ContentCredential {
        manifest,
        algo: signer.algorithm().to_string(),
        pubkey_hex: hex::encode(signer.public_key()),
        sig_hex: hex::encode(sig),
    }
}

/// Verify a credential against its embedded key AND that it matches the given content. Fail-closed.
pub fn verify(cred: &ContentCredential, content: &[u8]) -> bool {
    let pk = match hex::decode(&cred.pubkey_hex) { Ok(p) => p, Err(_) => return false };
    let sig = match hex::decode(&cred.sig_hex) { Ok(s) => s, Err(_) => return false };
    if !verify_ed25519(&pk, &crate::canonical::canonical_bytes(&cred.manifest), &sig) {
        return false;
    }
    cred.manifest.get("content_sha256").and_then(|v| v.as_str()) == Some(crate::canonical::sha256_hex_bytes(content).as_str())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sign::Ed25519Signer;

    #[test]
    fn stamp_verifies_and_detects_tampered_content() {
        let s = Ed25519Signer::generate();
        let content = b"a generated image bytes";
        let cred = stamp(content, "fable-5", "This media was generated by AI.", 1000, &s);
        assert!(verify(&cred, content), "credential verifies for the original content");
        assert!(!verify(&cred, b"different content"), "credential fails for altered content");
        let mut bad = cred.clone();
        bad.manifest["disclosure"] = json!("removed");
        assert!(!verify(&bad, content), "tampering the manifest breaks the signature");
    }
}
